title: Welcome to Math101
description: >
  Exploring Mathematics and Physics World
permalink: ':title/'
url: "https://mathblog.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: samuely09011520 #if your site has a twitter account, enter it here

# Author Settings
author: Samuel Yang # add your name
author-img: author.jpg # add your photo
about-author: # add description
social-twitter: samuely09011520 # add your Twitter handle
social-facebook: samuel.linyang.10 # add your Facebook handle
social-github: mathblog # add your Github handle
social-email: # add your Email address

# Disqus
discus-identifier: mathblog-1 # add your discus identifier

# Tracker
analytics: UA-120049095-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 12
paginate_path: "/page/:num"